### ISSUE TITLE
Cannot connect to my site.

### ISSUE THREAD

**Issue by LaserKaspar** [OnFreund/pyrisco#29]
Hi, i tried to connect to my site via its local IP and port 1000 and the pin to disarm my site. When trying to connect I get a timeout with CannotConnectError. 
Is there any other pin I should/could use? I tried the only one I know.
Thanks for the script anyways!

**Comment by OnFreund** [comment]
You can find some relevant info at https://www.home-assistant.io/integrations/risco#local-advanced

**Comment by lucacalcaterra** [comment]
Same issue here. @OnFreund Seems home assistant docs doesn't help. Probably newer firmware of my lightsys plus ?

**Comment by OnFreund** [comment]
Which pin code are you using? Did you try disabling cloud access in the panel?

**Comment by LaserKaspar** [comment]
I tried the one in home assistant docs (5678) and the code to disarm my site using my user (I think I am the Master User, how would I check?). Both did not work. 
I am running a WiComm Pro. I have not tried to disable cloud. How would I do that? (I don't have a cloud subscription).

**Comment by OnFreund** [comment]
I think the WiComm pro only has one network connection, so you'll have to disable cloud (not having a subscription is not enough). You can search for instructions online - my system supports two network connections, so I never had to do it myself.

**Comment by lucacalcaterra** [comment]
Update: in my case seems  a problem of lightsys plus panel. In fact can t connect with ip local connection , neither  with cs software. Risco bug ? Very strange. Sometimes works sometimes no

**Comment by OnFreund** [comment]
@lucacalcaterra Aren't you the developer of the MQTT bridge? If you have it running, it's going to use up one of the connections.

**Comment by robertboccia** [comment]
Works perfectly on NY prosys plus and the local is probably the best integration ever, thanks onfreund for developing this it's so much better than the crappy risco app

Robert Boccia
0824971422
________________________________

**Comment by lucacalcaterra** [comment]
> @lucacalcaterra Aren't you the developer of the MQTT bridge? If you have it running, it's going to use up one of the connections.

@OnFreund no , i'm testing on another panel of my parent house (mine i a lightsys 2 , older with single socket ip).  It's a lightsys plus , even not connected to cloud has a strange behaviour with local ip connection . I must reset ip address than works with ha and risco local connection; after some time stop works and can't nomore connect via local ip (i must hardware reset panel). Ps lightsys plus has multisocket connection.

**Comment by OnFreund** [comment]
And you mentioned it's also happening with CS software? Not sure I can help there...

**Comment by lucacalcaterra** [comment]
> And you mentioned it's also happening with CS software? Not sure I can help there...

@OnFreund i m realized it now... 😞

**Comment by LaserKaspar** [comment]
# Disabling Cloud
## Without CS
From: https://www.manualslib.com/manual/2892931/Risco-Wicomm-Pro.html?page=34&term=cloud&selected=2#manual
![image](https://github.com/user-attachments/assets/bba402f9-b47c-4b49-9854-868f3af061fe)

I can only access the programming menu via:
![image](https://github.com/user-attachments/assets/37c11e4d-b8f0-42b7-833a-51471e78db1c)

These buttons are not on the normal WiComm Pro. So I need an installer Keypad?

## With CS
So I installed CS Software (default logins seem to have worked) and disabled cloud (System -> Basic -> Cloud Enable unchecked) then pressing the save button on top. 
![image](https://github.com/user-attachments/assets/9f45a6ae-3b7d-48cc-9241-d65aff4b7bd6)

Is there any way to check if it has worked?
Do I need to perform some kind of reload/reload? If so how would I do that?

EDIT: I don't think the connection was active. I tried to access the event log and it presented me with stale data. After that I pressed the Communication -> Connect button and it failed. So I can't even disconnect from cloud...

# Tried Pyrisco Again:
I still can not connect to my panel via pyrisco. I tried all pins I know of. 

```py
import asyncio
from pyrisco import RiscoLocal

async def main():
    r = RiscoLocal("192.168.68.107", 1000, "5678") # tried: <mypin>, 5678, 1234
    print("Connecting")
    await r.connect()
    print("Connected")
    await r.disconnect()

asyncio.run(main())
```

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyrisco\local\risco_socket.py", line 33, in connect
    self._reader, self._writer = await asyncio.open_connection(self._host, self._port)
  File "C:\Python38\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Python38\lib\asyncio\base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "C:\Python38\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "C:\Python38\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Python38\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Python38\lib\asyncio\windows_events.py", line 595, in finish_connect
    ov.getresult()
OSError: [WinError 121] Das Zeitlimit für die Semaphore wurde erreicht

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/Felix/Desktop/pyrisco/pyriscotest.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:/Users/Felix/Desktop/pyrisco/pyriscotest.py", line 7, in main
    await r.connect()
  File "C:\Python38\lib\site-packages\pyrisco\local\risco_local.py", line 30, in connect
    await self._rs.connect()
  File "C:\Python38\lib\site-packages\pyrisco\local\risco_socket.py", line 50, in connect
    raise CannotConnectError from exc
pyrisco.common.CannotConnectError
```

## Checking Connections
Next step was checking if the panel was reachable from local network. It got assigned an IP by my router connected via LAN (under the name of Security_System) so I checked that using nmap:
```
nmap -Pn -p 1000 192.168.68.107

Starting Nmap 7.80 ( https://nmap.org ) at 2025-01-04 00:18 CET
Nmap scan report for 192.168.68.107
Host is up.

PORT     STATE    SERVICE
1000/tcp filtered cadlock
```

Seems like it's closed:
```
nmap -Pn 192.168.68.107

All 1000 scanned ports on 192.168.68.107 are filtered
```
Seems like more is closed...


```
sudo nmap -Pn -sS -p- 192.168.68.107

Starting Nmap 7.80 ( https://nmap.org ) at 2025-01-04 00:23 CET
Nmap scan report for 192.168.68.107
Host is up (0.0034s latency).
All 65535 scanned ports on 192.168.68.107 are filtered

Nmap done: 1 IP address (1 host up) scanned in 289.08 seconds
```
So every single port of this thing looks closed...

Which does not seem possible as I just connected to it via CS using 192.168.68.107:1000 so this whole section does not seem useful...

So i conclude, that the pincodes I have tried must be wrong? Is there any other way to check if a pincode should work? Next thing I would try is brute force all pins using the pyrisco. But I don't know if 1. that's possible, 2. it will trigger an alarm, 3. that's even the problem...
If I could do 1 code every second it would only take about 3hrs.

## Trying CS again
It might be possible that IP is disabled on my System?
https://www.manualslib.com/manual/2892931/Risco-Wicomm-Pro.html?page=98#manual

So I'll try connecting via usb.

**Comment by OnFreund** [comment]
I don't think the problem is the pincode, but in any case, unless it was changed by you or your installer, it's most likely 5678.

**Comment by lucacalcaterra** [comment]
> > @lucacalcaterra Aren't you the developer of the MQTT bridge? If you have it running, it's going to use up one of the connections.
> 
> @OnFreund no , i'm testing on another panel of my parent house (mine i a lightsys 2 , older with single socket ip). It's a lightsys plus , even not connected to cloud has a strange behaviour with local ip connection . I must reset ip address than works with ha and risco local connection; after some time stop works and can't nomore connect via local ip (i must hardware reset panel). Ps lightsys plus has multisocket connection.

... anyway... if reboot the panel connection works. Can be a faulty panel ? Very strange

**Comment by LaserKaspar** [comment]
> Update: in my case seems a problem of lightsys plus panel. In fact can t connect with ip local connection , neither with cs software. Risco bug ? Very strange. Sometimes works sometimes no

Was the same for me. I called my installer. He could reroute cloud connection to gprs so now IP access is free. Now I can access it via CS-Software.

My code was also confirmed to be 5678; Remote ID Code: 0001; MS Lock 000000

After that change I can now successfully use pyrisco and Home Assistant integration.
